routes/web.php
<?php

use App\Http\Controllers\IdeaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//ROUTE TO RENDER MAIN PAGE

Route::get('/', [IdeaController::class, 'index'])->name('idea.index');

//ROUTE TO RENDER SINGLE PAGE

Route::get('/ideas{idea:slug}', [IdeaController::class, 'show'])->name('idea.show');

require __DIR__ . '/auth.php';

app/Http/Livewire/AddComment.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Idea;
use App\Notifications\CommentAdded;
use Illuminate\Http\Response;
use Livewire\Component;

class AddComment extends Component
{
  public $idea;
  public $comment;
  protected $rules = [
    'comment' => 'required|min:4',
  ];

  public function mount(Idea $idea)
  {
    $this->idea = $idea;
  }

  public function addComment()
  {
    if (auth()->guest()) {
      abort(Response::HTTP_FORBIDDEN);
    }

    $this->validate();

    $newComment = Comment::create([
      'user_id' => auth()->id(),
      'idea_id' => $this->idea->id,
      'status_id' => 1,
      'body' => $this->comment,
    ]);

    $this->reset('comment');

    $this->idea->user->notify(new CommentAdded($newComment));

    $this->emit('commentWasAdded', 'Comment was posted!');
  }

  public function render()
  {
    return view('livewire.add-comment');
  }
}

app/Http/Livewire/CommentNotifications.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Idea;
use Illuminate\Http\Response;
use Illuminate\Notifications\DatabaseNotification;
use Livewire\Component;

class CommentNotifications extends Component
{
  const NOTIFICATION_THRESHOLD = 20;
  public $notifications;
  public $notificationCount;


  protected $listeners = ['getNotifications'];

  public function mount()
  {
    $this->notifications = collect([]);
    $this->getNotificationCount();
  }

  public function getNotificationCount()
  {
    $this->notificationCount = auth()->user()->unreadNotifications()->count();

    if ($this->notificationCount > self::NOTIFICATION_THRESHOLD) {
      $this->notificationCount = self::NOTIFICATION_THRESHOLD . '+';
    }
  }

  public function getNotifications()
  {
    $this->notifications = auth()->user()
      ->unreadNotifications()
      ->latest()
      ->take(self::NOTIFICATION_THRESHOLD)
      ->get();

  }

  public function markAsRead($notificationId)
  {
    if (auth()->guest()) {
      abort(Response::HTTP_FORBIDDEN);
    }

    $notification = DatabaseNotification::findOrFail($notificationId);
    $notification->markAsRead();

    $this->scrollToComment($notification);
  }

  public function scrollToComment($notification)
  {
    $idea = Idea::find($notification->data['idea_id']);
    if (!$idea) {
      session()->flash('error_message', 'This idea no longer exists!');

      return redirect()->route('idea.index');
    }

    $comment = Comment::find($notification->data['comment_id']);
    if (!$comment) {
      session()->flash('error_message', 'This comment no longer exists!');

      return redirect()->route('idea.index');
    }

    $comments = $idea->comments()->pluck('id');
    $indexOfComment = $comments->search($comment->id);

    $page = (int)($indexOfComment / $comment->getPerPage()) + 1;

    session()->flash('scrollToComment', $comment->id);

    return redirect()->route('idea.show', [
      'idea' => $notification->data['idea_slug'],
      'page' => $page,
    ]);
  }

  public function markAllAsRead()
  {
    if (auth()->guest()) {
      abort(Response::HTTP_FORBIDDEN);
    }

    auth()->user()->unreadNotifications->markAsRead();
    $this->getNotificationCount();
    $this->getNotifications();
  }

  public function render()
  {
    return view('livewire.comment-notifications');
  }
}

app/Http/Livewire/CreateIdea.php
<?php

namespace App\Http\Livewire;

use App\Models\Category;
use App\Models\Idea;
use App\Models\Vote;
use Illuminate\Http\Response;
use Livewire\Component;

class CreateIdea extends Component
{
  public $title;
  public $category = 1;
  public $description;

  protected $rules = [
    'title' => 'required|min:4',
    'category' => 'required|integer|exists:categories,id',
    'description' => 'required|min:4',
  ];

  public function createIdea()
  {
    if (auth()->guest()) {
      abort(Response::HTTP_FORBIDDEN);
    }

    $this->validate();

    $idea = Idea::create([
      'user_id' => auth()->id(),
      'category_id' => $this->category,
      'status_id' => 1,
      'title' => $this->title,
      'description' => $this->description,
    ]);

    $idea->vote(auth()->user());

    session()->flash('success_message', 'Idea was added successfully!');

    $this->reset();

    return redirect()->route('idea.index');
  }

  public function render()
  {
    return view('livewire.create-idea', [
      'categories' => Category::all(),
    ]);
  }
}

app/Http/Livewire/DeleteComment.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use Illuminate\Http\Response;
use Livewire\Component;

class DeleteComment extends Component
{
  public ?Comment $comment;

  protected $listeners = ['setDeleteComment'];

  public function setDeleteComment($commentId)
  {
    $this->comment = Comment::findOrFail($commentId);

    $this->emit('deleteCommentWasSet');
  }

  public function deleteComment()
  {
    if (auth()->guest() || auth()->user()->cannot('delete', $this->comment)) {
      abort(Response::HTTP_FORBIDDEN);
    }

    Comment::destroy($this->comment->id);
    $this->comment = null;
    $this->emit('commentWasDeleted', 'Comment was deleted!');
  }

  public function render()
  {
    return view('livewire.delete-comment');
  }
}

app/Http/Livewire/DeleteIdea.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Idea;
use App\Models\Vote;
use Illuminate\Http\Response;
use Livewire\Component;

class DeleteIdea extends Component
{
  public $idea;

  public function mount(Idea $idea)
  {
    $this->idea = $idea;
  }

  public function deleteIdea()
  {
    if (auth()->guest() || auth()->user()->cannot('delete', $this->idea)) {
      abort(Response::HTTP_FORBIDDEN);
    }

    Idea::destroy($this->idea->id);

    session()->flash('success_message', 'Idea was deleted successfully!');

    return redirect()->route('idea.index');
  }

  public function render()
  {
    return view('livewire.delete-idea');
  }
}

app/Http/Livewire/EditComment.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use Illuminate\Http\Response;
use Livewire\Component;

class EditComment extends Component
{
  public Comment $comment;
  public $body;

  protected $rules = [
    'body' => 'required|min:4',
  ];

  protected $listeners = ['setEditComment'];

  public function setEditComment($commentId)
  {
    $this->comment = Comment::findOrFail($commentId);
    $this->body = $this->comment->body;

    $this->emit('editCommentWasSet');
  }

  public function updateComment()
  {
    if (auth()->guest() || auth()->user()->cannot('update', $this->comment)) {
      abort(Response::HTTP_FORBIDDEN);
    }

    $this->validate();

    $this->comment->body = $this->body;
    $this->comment->save();

    $this->emit('commentWasUpdated', 'Comment was updated!');
  }

  public function render()
  {
    return view('livewire.edit-comment');
  }
}

app/Http/Livewire/EditIdea.php
<?php

namespace App\Http\Livewire;

use App\Models\Category;
use App\Models\Idea;
use Illuminate\Http\Response;
use Livewire\Component;

class EditIdea extends Component
{
  public $idea;
  public $title;
  public $category;
  public $description;

  protected $rules = [
    'title' => 'required|min:4',
    'category' => 'required|integer|exists:categories,id',
    'description' => 'required|min:10',
  ];

  public function mount(Idea $idea)
  {
    $this->idea = $idea;
    $this->title = $idea->title;
    $this->category = $idea->category_id;
    $this->description = $idea->description;
  }

  public function updateIdea()
  {
    if (auth()->guest() || auth()->user()->cannot('update', $this->idea)) {
      abort(Response::HTTP_FORBIDDEN);
    }

    $this->validate();

    $this->idea->update([
      'title' => $this->title,
      'category_id' => $this->category,
      'description' => $this->description
    ]);

    $this->emit('ideaWasUpdated', 'Idea was updated successfully!');
  }


  public function render()
  {
    return view('livewire.edit-idea', [
      'categories' => Category::all()
    ]);
  }
}

app/Http/Livewire/IdeaComment.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use Livewire\Component;

class IdeaComment extends Component
{
  public $comment;
  public $ideaUserId;

  protected $listeners = [
    'commentWasUpdated',
    'commentWasMarkedAsSpam',
    'commentWasMarkedAsNotSpam',
  ];

  public function commentWasUpdated()
  {
    $this->comment->refresh();
  }

  public function commentWasMarkedAsSpam()
  {
    $this->comment->refresh();
  }

  public function commentWasMarkedAsNotSpam()
  {
    $this->comment->refresh();
  }

  public function mount(Comment $comment, $ideaUserId)
  {
    $this->comment = $comment;
    $this->ideaUserId = $ideaUserId;
  }

  public function render()
  {
    return view('livewire.idea-comment');
  }
}

app/Http/Livewire/IdeaComments.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Idea;
use Livewire\Component;
use Livewire\WithPagination;

class IdeaComments extends Component
{
  use WithPagination;

  public $idea;

  protected $listeners = ['commentWasAdded', 'commentWasDeleted', 'statusWasUpdated'];

  public function commentWasAdded()
  {
    $this->idea->refresh();
    $this->goToPage($this->idea->comments()->paginate()->lastPage());
  }

  public function statusWasUpdated()
  {
    $this->idea->refresh();
    $this->goToPage($this->idea->comments()->paginate()->lastPage());
  }

  public function commentWasDeleted()
  {
    $this->idea->refresh();
    $this->goToPage(1);
  }

  public function mount(Idea $idea)
  {
    $this->idea = $idea;
  }

  public function render()
  {
    return view('livewire.idea-comments', [
      // 'comments' => $this->idea->comments()->paginate()->withQueryString(),
      'comments' => Comment::with(['user', 'status'])->where('idea_id', $this->idea->id)->paginate()->withQueryString(),
    ]);
  }
}

app/Http/Livewire/IdeaIndex.php
<?php

namespace App\Http\Livewire;

use App\Exceptions\DuplicateVoteException;
use App\Exceptions\VoteNotFoundException;
use App\Models\Idea;
use Livewire\Component;

class IdeaIndex extends Component
{
    public $idea;

    public $votesCount;

    public $hasVoted;

    public function mount(Idea $idea, $votesCount)
    {
        $this->idea = $idea;
        $this->votesCount = $votesCount;
        $this->hasVoted = $idea->voted_by_user;
    }

    public function vote()
    {
        if (!auth()->check()) {
            return redirect(route('login'));
        }

        if ($this->hasVoted) {
            try {
                $this->idea->removeVote(auth()->user());
            } catch (VoteNotFoundException $e) {
                // do nothing
            }
            $this->votesCount--;
            $this->hasVoted = false;
        } else {
            try {
                $this->idea->vote(auth()->user());
            } catch (DuplicateVoteException $e) {
                // do nothing
            }
            $this->votesCount++;
            $this->hasVoted = true;
        }
    }

    public function render()
    {
        return view('livewire.idea-index');
    }
}

app/Http/Livewire/IdeaShow.php
<?php

namespace App\Http\Livewire;

use App\Exceptions\DuplicateVoteException;
use App\Exceptions\VoteNotFoundException;
use App\Models\Idea;
use Livewire\Component;

class IdeaShow extends Component
{
  public $idea;
  public $votesCount;
  public $hasVoted;

  protected $listeners = [
    'statusWasUpdated',
    'ideaWasUpdated',
    'ideaWasMarkedAsSpam',
    'ideaWasMarkedAsNotSpam',
    'commentWasAdded',
    'commentWasDeleted',
  ];

  public function mount(Idea $idea, $votesCount)
  {
    $this->idea = $idea;
    $this->votesCount = $votesCount;
    $this->hasVoted = $idea->isVotedByUser(auth()->user());
  }

  public function statusWasUpdated()
  {
    $this->idea->refresh();
  }

  public function ideaWasUpdated()
  {
    $this->idea->refresh();
  }

  public function ideaWasMarkedAsSpam()
  {
    $this->idea->refresh();
  }

  public function ideaWasMarkedAsNotSpam()
  {
    $this->idea->refresh();
  }

  public function commentWasAdded()
  {
    $this->idea->refresh();
  }

  public function commentWasDeleted()
  {
    $this->idea->refresh();
  }

  public function vote()
  {
    if (!auth()->check()) {
      return redirect(route('login'));
    }

    if ($this->hasVoted) {
      try {
        $this->idea->removeVote(auth()->user());
      } catch (VoteNotFoundException $e) {
        // do nothing
      }
      $this->votesCount--;
      $this->hasVoted = false;
    } else {
      try {
        $this->idea->vote(auth()->user());
      } catch (DuplicateVoteException $e) {
        // do nothing
      }
      $this->votesCount++;
      $this->hasVoted = true;
    }
  }

  public function render()
  {
    return view('livewire.idea-show');
  }
}

app/Http/Livewire/IdeasIndex.php
<?php

namespace App\Http\Livewire;

use App\Models\Category;
use App\Models\Idea;
use App\Models\Status;
use App\Models\Vote;
use Livewire\Component;
use Livewire\WithPagination;

class IdeasIndex extends Component
{
  use WithPagination;

  public $status;
  public $category;
  public $filter;
  public $search;

  protected $queryString = [
    'status',
    'category',
    'filter',
    'search',
  ];

  protected $listeners = ['queryStringUpdatedStatus'];

  public function mount()
  {
    $this->status = request()->status ?? 'All';
  }

  public function updatingCategory()
  {
    $this->resetPage();
  }

  public function updatingFilter()
  {
    $this->resetPage();
  }

  public function updatingSearch()
  {
    $this->resetPage();
  }

  public function updatedFilter()
  {
    if ($this->filter === 'My Ideas') {
      if (!auth()->check()) {
        return redirect()->route('login');
      }
    }
  }

  public function queryStringUpdatedStatus($newStatus)
  {
    $this->resetPage();
    $this->status = $newStatus;
  }

  public function render()
  {
    $statuses = Status::all()->pluck('id', 'name');
    $categories = Category::all();

    return view('livewire.ideas-index', [
      'ideas' => Idea::with('user', 'category', 'status')
        ->when($this->status && $this->status !== 'All', function ($query) use ($statuses) {
          return $query->where('status_id', $statuses->get($this->status));
        })->when($this->category && $this->category !== 'All Categories', function ($query) use ($categories) {
          return $query->where('category_id', $categories->pluck('id', 'name')->get($this->category));
        })->when($this->filter && $this->filter === 'Top Voted', function ($query) {
          return $query->orderByDesc('votes_count');
        })->when($this->filter && $this->filter === 'My Ideas', function ($query) {
          return $query->where('user_id', auth()->id());
        })->when($this->filter && $this->filter === 'Spam Ideas', function ($query) {
          return $query->where('spam_reports', '>', 0)->orderByDesc('spam_reports');
        })->when($this->filter && $this->filter === 'Spam Comments', function ($query) {
          return $query->whereHas('comments', function ($query) {
            $query->where('spam_reports', '>', 0);
          });
        })->when(strlen($this->search) >= 3, function ($query) {
          return $query->where('title', 'like', '%' . $this->search . '%');
        })
        ->addSelect(['voted_by_user' => Vote::select('id')
          ->where('user_id', auth()->id())
          ->whereColumn('idea_id', 'ideas.id')
        ])
        ->withCount('votes')
        ->withCount('comments')
        ->orderBy('id', 'desc')
        ->simplePaginate()
        ->withQueryString(),
      'categories' => $categories,
    ]);
  }
}

app/Http/Livewire/MarkCommentAsNotSpam.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use Illuminate\Http\Response;
use Livewire\Component;

class MarkCommentAsNotSpam extends Component
{
  public Comment $comment;

  protected $listeners = ['setMarkAsNotSpamComment'];

  public function setMarkAsNotSpamComment($commentId)
  {
    $this->comment = Comment::findOrFail($commentId);

    $this->emit('markAsNotSpamCommentWasSet');
  }

  public function markAsNotSpam()
  {
    if (auth()->guest() || ! auth()->user()->isAdmin()) {
      abort(Response::HTTP_FORBIDDEN);
    }

    $this->comment->spam_reports = 0;
    $this->comment->save();

    $this->emit('commentWasMarkedAsNotSpam', 'Comment spam counter was reset!');
  }

  public function render()
  {
    return view('livewire.mark-comment-as-not-spam');
  }
}

app/Http/Livewire/MarkIdeaAsNotSpam.php
<?php

namespace App\Http\Livewire;

use App\Models\Idea;
use Illuminate\Http\Response;
use Livewire\Component;

class MarkIdeaAsNotSpam extends Component
{
  public $idea;

  public function mount(Idea $idea)
  {
    $this->idea = $idea;
  }

  public function markAsNotSpam()
  {
    if (auth()->guest() || !auth()->user()->isAdmin()) {
      abort(Response::HTTP_FORBIDDEN);
    }

    $this->idea->spam_reports = 0;
    $this->idea->save();

    $this->emit('ideaWasMarkedAsNotSpam','Spam counter was reset!');
  }

  public function render()
  {
    return view('livewire.mark-idea-as-not-spam');
  }
}

resources/views/livewire/add-comment.blade.php
<div
  x-data="{ isOpen: false }"
  x-init="
        Livewire.on('commentWasAdded', () => {
            isOpen = false
        })
        Livewire.hook('message.processed', (message, component) => {
            {{-- Pagination --}}
    if (['gotoPage', 'previousPage', 'nextPage'].includes(message.updateQueue[0].method)) {
        const firstComment = document.querySelector('.comment-container:first-child')
        firstComment.scrollIntoView({ behavior: 'smooth'})
    }
{{-- Adding Comment --}}
    if (['commentWasAdded', 'statusWasUpdated'].includes(message.updateQueue[0].payload.event)
     && message.component.fingerprint.name === 'idea-comments') {
        const lastComment = document.querySelector('.comment-container:last-child')
        lastComment.scrollIntoView({ behavior: 'smooth'})
        lastComment.classList.add('bg-green-50')
        setTimeout(() => {
            lastComment.classList.remove('bg-green-50')
        }, 5000)
    }
})
@if (session('scrollToComment'))
    const commentToScrollTo = document.querySelector('#comment-{{ session('scrollToComment') }}')
            commentToScrollTo.scrollIntoView({ behavior: 'smooth'})
            commentToScrollTo.classList.add('bg-green-50')
            setTimeout(() => {
                commentToScrollTo.classList.remove('bg-green-50')
            }, 5000)
        @endif
    "
  class="relative"
>
  <button
    type="button"
    @click="
            isOpen = !isOpen
            if (isOpen) {
                $nextTick(() => $refs.comment.focus())
            }
        "
    class="flex items-center justify-center h-11 w-32 text-sm bg-blue text-white font-semibold rounded-xl border border-blue hover:bg-blue-hover transition duration-150 ease-in px-6 py-3"
  >
    Reply
  </button>
  <div
    class="absolute z-10 w-64 md:w-104 text-left font-semibold text-sm bg-white shadow-dialog rounded-xl mt-2"
    x-cloak
    x-show.transition.origin.top.left="isOpen"
    @click.away="isOpen = false"
    @keydown.escape.window="isOpen = false"
  >
    @auth
      <form wire:submit.prevent="addComment" action="#" class="space-y-4 px-4 py-6">
        <div>
          <textarea x-ref="comment" wire:model="comment" name="post_comment" id="post_comment" cols="30" rows="4"
                    class="w-full text-sm bg-gray-100 rounded-xl placeholder-gray-900 border-none px-4 py-2"
                    placeholder="Go ahead, don't be shy. Share your thoughts..." required></textarea>

          @error('comment')
          <p class="text-red text-xs mt-1">{{ $message }}</p>
          @enderror
        </div>

        <div class="flex flex-col md:flex-row items-center md:space-x-3">
          <button
            type="submit"
            class="flex items-center justify-center h-11 w-full md:w-1/2 text-sm bg-blue text-white font-semibold rounded-xl border border-blue hover:bg-blue-hover transition duration-150 ease-in px-6 py-3"
          >
            Post Comment
          </button>
          <button
            type="button"
            class="flex items-center justify-center w-full md:w-32 h-11 text-xs bg-gray-200 font-semibold rounded-xl border border-gray-200 hover:border-gray-400 transition duration-150 ease-in px-6 py-3 mt-2 md:mt-0"
          >
            <svg class="text-gray-600 w-4 transform -rotate-45" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"/>
            </svg>
            <span class="ml-1">Attach</span>
          </button>
        </div>

      </form>
    @else
      <div class="px-4 py-6">
        <p class="font-normal">Please login or create an account to post a comment.</p>
        <div class="flex items-center space-x-3 mt-8">
          <a
            href="{{ route('login') }}"
            class="w-1/2 h-11 text-sm text-center bg-blue text-white font-semibold rounded-xl hover:bg-blue-hover transition duration-150 ease-in px-6 py-3"
          >
            Login
          </a>
          <a
            href="{{ route('register') }}"
            class="flex items-center justify-center w-1/2 h-11 text-xs bg-gray-200 font-semibold rounded-xl border border-gray-200 hover:border-gray-400 transition duration-150 ease-in px-6 py-3"
          >
            Sign Up
          </a>
        </div>
      </div>
    @endauth
  </div>
</div>

resources/views/livewire/delete-comment.blade.php
<x-modal-confirm
  livewire-event-to-open-modal="deleteCommentWasSet"
  event-to-close-modal="commentWasDeleted"
  modal-title="Delete Comment"
  modal-description="Are you sure you want to delete this comment? This action cannot be undone."
  modal-confirm-button-text="Delete"
  wire-click="deleteComment"
/>

resources/views/livewire/idea-comments.blade.php
<div>
  @if($comments->isNotEmpty())
    <div class="comments-container relative space-y-6 md:ml-22 pt-4 my-8 mt-1">
      @foreach($comments as $comment)
        <livewire:idea-comment
          :key="$comment->id"
          :comment="$comment"
          :ideaUserId="$idea->user->id"
        />
      @endforeach

    </div>
    <div class="my-8 md:ml-22">
      {{ $comments->onEachSide(1)->links() }}
    </div>
  @else

    <div class="mx-auto w-70 mt-12">
      <div class="text-gray-400 text-center font-bold mt-6">No comments yet...be the first!</div>
    </div>
</div>
@endif

resources/views/livewire/idea-index.blade.php
<div
  x-data
  @click="
        const clicked = $event.target
        const target = clicked.tagName.toLowerCase()
        const ignores = ['button', 'svg', 'path', 'a']
        if (! ignores.includes(target)) {
            clicked.closest('.idea-container').querySelector('.idea-link').click()
        }
    "
  class="idea-container hover:shadow-card transition duration-150 ease-in bg-white rounded-xl flex cursor-pointer"
>
  <div class="hidden md:block border-r border-gray-100 px-5 py-8">
    <div class="text-center">
      <div class="font-semibold text-2xl @if ($hasVoted) text-blue @endif">{{ $votesCount }}</div>
      <div class="text-gray-500">Votes</div>
    </div>

    <div class="mt-8">
      @if ($hasVoted)
        <button wire:click.prevent="vote"
                class="w-20 bg-blue text-white border border-blue hover:bg-blue-hover font-bold text-xxs uppercase rounded-xl transition duration-150 ease-in px-4 py-3">
          Voted
        </button>
      @else
        <button wire:click.prevent="vote"
                class="w-20 bg-gray-200 border border-gray-200 hover:border-gray-400 font-bold text-xxs uppercase rounded-xl transition duration-150 ease-in px-4 py-3">
          Vote
        </button>
      @endif
    </div>
  </div>
  <div class="flex flex-col md:flex-row flex-1 px-2 py-6">
    <div class="flex-none mx-2 md:mx-0">
      <a href="#">
        <img src="{{ $idea->user->getAvatar() }}" alt="avatar" class="w-14 h-14 rounded-xl">
      </a>
    </div>
    <div class="w-full flex flex-col justify-between mx-2 md:mx-4">
      <h4 class="text-xl font-semibold mt-2 md:mt-0">
        <a href="{{ route('idea.show', $idea) }}" class="idea-link hover:underline">{{ $idea->title }}</a>
      </h4>
      <div class="text-gray-600 mt-3 line-clamp-3">
        @admin
        @if ($idea->spam_reports > 0)
          <div class="text-red mb-2">Spam Reports: {{ $idea->spam_reports }}</div>
        @endif
        @endadmin
        {{ $idea->description }}
      </div>

      <div class="flex flex-col md:flex-row md:items-center justify-between mt-6">
        <div class="flex items-center text-xs text-gray-400 font-semibold space-x-2">
          <div>{{ $idea->created_at->diffForHumans() }}</div>
          <div>&bull;</div>
          <div>{{ $idea->category->name }}</div>
          <div>&bull;</div>
          <div wire:ignore class="text-gray-900">{{ $idea->comments_count }} comments</div>
        </div>
        <div
          x-data="{ isOpen: false }"
          class="flex items-center space-x-2 mt-4 md:mt-0"
        >
          <div
            class="{{ 'status-'.Str::kebab($idea->status->name) }} text-xxs font-bold uppercase leading-none rounded-full text-center w-28 h-7 py-2 px-4">{{ $idea->status->name }}</div>
        </div>

        <div class="flex items-center md:hidden mt-4 md:mt-0">
          <div class="bg-gray-100 text-center rounded-xl h-10 px-4 py-2 pr-8">
            <div class="text-sm font-bold leading-none @if ($hasVoted) text-blue @endif">{{ $votesCount }}</div>
            <div class="text-xxs font-semibold leading-none text-gray-400">Votes</div>
          </div>
          @if ($hasVoted)
            <button
              wire:click.prevent="vote"
              class="w-20 bg-blue text-white border border-blue font-bold text-xxs uppercase rounded-xl hover:bg-blue-hover transition duration-150 ease-in px-4 py-3 -mx-5"
            >
              Voted
            </button>
          @else
            <button
              wire:click.prevent="vote"
              class="w-20 bg-gray-200 border border-gray-200 font-bold text-xxs uppercase rounded-xl hover:border-gray-400 transition duration-150 ease-in px-4 py-3 -mx-5"
            >
              Vote
            </button>
          @endif
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/livewire/mark-comment-as-spam.blade.php
<x-modal-confirm
  livewire-event-to-open-modal="markAsSpamCommentWasSet"
  event-to-close-modal="commentWasMarkedAsSpam"
  modal-title="Mark Comment as Spam"
  modal-description="Are you sure you want this comment as spam?"
  modal-confirm-button-text="Mark as Spam"
  wire-click="markAsSpam"
/>